package net.modificationstation.stationapi.api.vanillafix.item;

import net.minecraft.item.ItemBase;

public final class Items {

    // BLOCKS
    public static ItemBase
            STONE,
            GRASS_BLOCK,
            DIRT,
            COBBLESTONE,
            PLANKS,

    // SAPLING MODIFIED BY STATIONAPI TO EXPAND METADATA VARIATIONS INTO SEPARATE BLOCKS
            OAK_SAPLING,
            SPRUCE_SAPLING,
            BIRCH_SAPLING,
    // SAPLING END

            BEDROCK,
            FLOWING_WATER,
            WATER,
            FLOWING_LAVA,
            LAVA,
            SAND,
            GRAVEL,
            GOLD_ORE,
            IRON_ORE,
            COAL_ORE,

    // LOG MODIFIED BY STATIONAPI TO EXPAND METADATA VARIATIONS INTO SEPARATE BLOCKS
            OAK_LOG,
            SPRUCE_LOG,
            BIRCH_LOG,
    // LOG END

    // LEAVES MODIFIED BY STATIONAPI TO EXPAND METADATA VARIATIONS INTO SEPARATE BLOCKS
            OAK_LEAVES,
            SPRUCE_LEAVES,
            BIRCH_LEAVES,
    // SAPLING END

            SPONGE,
            GLASS,
            LAPIS_ORE,
            LAPIS_BLOCK,
            DISPENSER,
            SANDSTONE,
            NOTE_BLOCK,
            POWERED_RAIL,
            DETECTOR_RAIL,
            STICKY_PISTON,
            COBWEB,
            GRASS,
            DEAD_BUSH,
            PISTON,
            PISTON_HEAD,

    // WOOL MODIFIED BY STATIONAPI TO EXPAND METADATA VARIATIONS INTO SEPARATE BLOCKS
            BLACK_WOOL,
            RED_WOOL,
            GREEN_WOOL,
            BROWN_WOOL,
            BLUE_WOOL,
            PURPLE_WOOL,
            CYAN_WOOL,
            LIGHT_GRAY_WOOL,
            GRAY_WOOL,
            PINK_WOOL,
            LIME_WOOL,
            YELLOW_WOOL,
            LIGHT_BLUE_WOOL,
            MAGENTA_WOOL,
            ORANGE_WOOL,
            WHITE_WOOL,
    // WOOL END

            MOVING_PISTON,
            DANDELION,
            ROSE,
            BROWN_MUSHROOM,
            RED_MUSHROOM,
            GOLD_BLOCK,
            IRON_BLOCK,
            DOUBLE_SLAB,
            SLAB,
            BRICKS,
            TNT,
            BOOKSHELF,
            MOSSY_COBBLESTONE,
            OBSIDIAN,
            TORCH,
            FIRE,
            SPAWNER,
            OAK_STAIRS,
            CHEST,
            REDSTONE_WIRE,
            DIAMOND_ORE,
            DIAMOND_BLOCK,
            CRAFTING_TABLE,
            FARMLAND,
            FURNACE,
            FURNACE_LIT,
            LADDER,
            RAIL,
            COBBLESTONE_STAIRS,
            WALL_SIGN,
            LEVER,
            OAK_PRESSURE_PLATE,
            STONE_PRESSURE_PLATE,
            REDSTONE_ORE,
            REDSTONE_ORE_LIT,
            REDSTONE_TORCH,
            REDSTONE_TORCH_LIT,
            BUTTON,
            SNOW,
            ICE,
            SNOW_BLOCK,
            CACTUS,
            CLAY,
            JUKEBOX,
            FENCE,
            PUMPKIN,
            NETHERRACK,
            SOUL_SAND,
            GLOWSTONE,
            PORTAL,
            JACK_O_LANTERN,
            REPEATER_LIT,
            LOCKED_CHEST,
            TRAPDOOR,

    // ITEMS
            IRON_SHOVEL,
            IRON_PICKAXE,
            IRON_AXE,
            FLINT_AND_STEEL,
            APPLE,
            BOW,
            ARROW,
            COAL,
            DIAMOND,
            IRON_INGOT,
            GOLD_INGOT,
            IRON_SWORD,
            WOODEN_SWORD,
            WOODEN_SHOVEL,
            WOODEN_PICKAXE,
            WOODEN_AXE,
            STONE_SWORD,
            STONE_SHOVEL,
            STONE_PICKAXE,
            STONE_AXE,
            DIAMOND_SWORD,
            DIAMOND_SHOVEL,
            DIAMOND_PICKAXE,
            DIAMOND_AXE,
            STICK,
            BOWL,
            MUSHROOM_STEW,
            GOLDEN_SWORD,
            GOLDEN_SHOVEL,
            GOLDEN_PICKAXE,
            GOLDEN_AXE,
            STRING,
            FEATHER,
            GUNPOWDER,
            WOODEN_HOE,
            STONE_HOE,
            IRON_HOE,
            DIAMOND_HOE,
            GOLDEN_HOE,
            WHEAT_SEEDS,
            WHEAT,
            BREAD,
            LEATHER_HELMET,
            LEATHER_CHESTPLATE,
            LEATHER_LEGGINGS,
            LEATHER_BOOTS,
            CHAINMAIL_HELMET,
            CHAINMAIL_CHESTPLATE,
            CHAINMAIL_LEGGINGS,
            CHAINMAIL_BOOTS,
            IRON_HELMET,
            IRON_CHESTPLATE,
            IRON_LEGGINGS,
            IRON_BOOTS,
            DIAMOND_HELMET,
            DIAMOND_CHESTPLATE,
            DIAMOND_LEGGINGS,
            DIAMOND_BOOTS,
            GOLDEN_HELMET,
            GOLDEN_CHESTPLATE,
            GOLDEN_LEGGINGS,
            GOLDEN_BOOTS,
            FLINT,
            PORKCHOP,
            COOKED_PORKCHOP,
            PAINTING,
            GOLDEN_APPLE,
            SIGN,
            OAK_DOOR,
            BUCKET,
            WATER_BUCKET,
            LAVA_BUCKET,
            MINECART,
            SADDLE,
            IRON_DOOR,
            REDSTONE,
            SNOWBALL,
            OAK_BOAT,
            LEATHER,
            MILK_BUCKET,
            BRICK,
            CLAY_BALL,
            SUGAR_CANE,
            PAPER,
            BOOK,
            SLIME_BALL,
            CHEST_MINECART,
            FURNACE_MINECART,
            EGG,
            COMPASS,
            FISHING_ROD,
            CLOCK,
            GLOWSTONE_DUST,
            FISH,
            COOKED_FISH,
            DYE,
            BONE,
            SUGAR,
            CAKE,
            BED,
            REPEATER,
            COOKIE,
            MAP,
            SHEARS,
            MUSIC_DISC_13,
            MUSIC_DISC_CAT;

    public static ItemBase woolMetaToBlock(int meta) {
        return switch (meta) {
            case 0 -> WHITE_WOOL;
            case 1 -> ORANGE_WOOL;
            case 2 -> MAGENTA_WOOL;
            case 3 -> LIGHT_BLUE_WOOL;
            case 4 -> YELLOW_WOOL;
            case 5 -> LIME_WOOL;
            case 6 -> PINK_WOOL;
            case 7 -> GRAY_WOOL;
            case 8 -> LIGHT_GRAY_WOOL;
            case 9 -> CYAN_WOOL;
            case 10 -> PURPLE_WOOL;
            case 11 -> BLUE_WOOL;
            case 12 -> BROWN_WOOL;
            case 13 -> GREEN_WOOL;
            case 14 -> RED_WOOL;
            case 15 -> BLACK_WOOL;
            default -> throw new IllegalStateException("Unexpected value: " + meta);
        };
    }
}
