package net.modificationstation.stationapi.api.registry.tag;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;
import net.minecraft.block.Block;
import net.modificationstation.stationapi.api.registry.BlockRegistry;
import net.modificationstation.stationapi.api.tag.TagKey;
import net.modificationstation.stationapi.api.util.Identifier;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public final class BlockTags {
    public static final TagKey<Block>
            BOOKSHELVES = of("c:bookshelves"),
            BRICK_BLOCKS = of("c:brick_blocks"),
            NORMAL_BRICK_BLOCKS = of("c:brick_blocks/normal"),
            BUTTONS = of("c:buttons"),
            STONE_BUTTONS = of("c:buttons/stone"),
            CACTI = of("c:cacti"),
            CHESTS = of("c:chests"),
            WOODEN_CHESTS = of("c:chests/wooden"),
            CLAY_BLOCKS = of("c:clay_blocks"),
            COBBLESTONES = of("c:cobblestones"),
            MOSSY_COBBLESTONES = of("c:cobblestones/mossy"),
            NORMAL_COBBLESTONES = of("c:cobblestones/normal"),
            DIRTS = of("c:dirts"),
            DOORS = of("c:doors"),
            IRON_DOORS = of("c:doors/iron"),
            WOODEN_DOORS = of("c:doors/wooden"),
            OAK_DOORS = of("c:doors/wooden/oak"),
            FENCE_GATES = of("c:fence_gates"),
            WOODEN_FENCE_GATES = of("c:fence_gates/wooden"),
            FENCES = of("c:fences"),
            WOODEN_FENCES = of("c:fences/wooden"),
            OAK_FENCES = of("c:fences/wooden/oak"),
            FLOWERS = of("c:flowers"),
            NORMAL_FLOWERS = of("c:flowers/normal"),
            TALL_FLOWERS = of("c:flowers/tall"),
            GLASS_BLOCKS = of("c:glass_blocks"),
            COLORLESS_GLASS_BLOCKS = of("c:glass_blocks/colorless"),
            GRASS_BLOCKS = of("c:grass_blocks"),
            GRAVELS = of("c:gravels"),
            LADDERS = of("c:ladders"),
            WOODEN_LADDERS = of("c:ladders/wooden"),
            OAK_LADDERS = of("c:ladders/wooden/oak"),
            LEAVES = of("c:leaves"),
            LOGS = of("c:logs"),
            MUSHROOMS = of("c:mushrooms"),
            BROWN_MUSHROOMS = of("c:mushrooms/brown"),
            RED_MUSHROOMS = of("c:mushrooms/red"),
            NETHERRACKS = of("c:netherracks"),
            OBSIDIANS = of("c:obsidians"),
            NORMAL_OBSIDIANS = of("c:obsidians/normal"),
            ORE_BEARING_GROUND_NETHERRACK = of("c:ore_bearing_ground/netherrack"),
            ORE_BEARING_GROUND_STONE = of("c:ore_bearing_ground/stone"),
            ORES = of("c:ores"),
            COAL_ORES = of("c:ores/coal"),
            DIAMOND_ORES = of("c:ores/diamond"),
            GOLD_ORES = of("c:ores/gold"),
            IRON_ORES = of("c:ores/iron"),
            LAPIS_ORES = of("c:ores/lapis"),
            REDSTONE_ORES = of("c:ores/redstone"),
            PLANKS = of("c:planks"),
            OAK_PLANKS = of("c:planks/oak"),
            PRESSURE_PLATES = of("c:pressure_plates"),
            STONE_PRESSURE_PLATES = of("c:pressure_plates/stone"),
            WOODEN_PRESSURE_PLATES = of("c:pressure_plates/wooden"),
            OAK_PRESSURE_PLATES = of("c:pressure_plates/wooden/oak"),
            PUMPKINS = of("c:pumpkins"),
            JACK_O_LANTERNS = of("c:pumpkins/jack_o_lanterns"),
            NORMAL_PUMPKINS = of("c:pumpkins/normal"),
            RAILS = of("c:rails"),
            SANDS = of("c:sands"),
            NORMAL_SANDS = of("c:sands/normal"),
            SANDSTONE_BLOCKS = of("c:sandstone/blocks"),
            NORMAL_SANDSTONE_BLOCKS = of("c:sandstone/normal_blocks"),
            SAPLINGS = of("c:saplings"),
            SIGNS = of("c:signs"),
            WOODEN_SIGNS = of("c:signs/wooden"),
            OAK_SIGNS = of("c:signs/wooden/oak"),
            OAK_STANDING_SIGNS = of("c:signs/wooden/oak/standing"),
            OAK_WALL_SIGNS = of("c:signs/wooden/oak/wall"),
            SNOW = of("c:snow"),
            STAIRS = of("c:stairs"),
            COBBLESTONE_STAIRS = of("c:stairs/cobblestone"),
            WOODEN_STAIRS = of("c:stairs/wooden"),
            OAK_STAIRS = of("c:stairs/wooden/oak"),
            STONES = of("c:stones"),
            STORAGE_BLOCKS = of("c:storage_blocks"),
            DIAMOND_STORAGE_BLOCKS = of("c:storage_blocks/diamond"),
            GOLD_STORAGE_BLOCKS = of("c:storage_blocks/gold"),
            IRON_STORAGE_BLOCKS = of("c:storage_blocks/iron"),
            LAPIS_STORAGE_BLOCKS = of("c:storage_blocks/lapis"),
            TRAPDOORS = of("c:trapdoors"),
            WOODEN_TRAPDOORS = of("c:trapdoors/wooden"),
            OAK_TRAPDOORS = of("c:trapdoors/wooden/oak"),
            WOOLS = of("c:wools"),

            INFINIBURN = of("infiniburn"),
            MINEABLE_AXE = of("mineable/axe"),
            MINEABLE_HOE = of("mineable/hoe"),
            MINEABLE_PICKAXE = of("mineable/pickaxe"),
            MINEABLE_SHEARS = of("mineable/shears"),
            MINEABLE_SHOVEL = of("mineable/shovel"),
            MINEABLE_SWORD = of("mineable/sword"),
            NEEDS_DIAMOND_TOOL = of("needs_diamond_tool"),
            NEEDS_IRON_TOOL = of("needs_iron_tool"),
            NEEDS_STONE_TOOL = of("needs_stone_tool");

    private static TagKey<Block> of(String id) {
        return TagKey.of(BlockRegistry.KEY, Identifier.of(id));
    }
}
